export const audioCaptions = [
        {time: 0, text: "Welcome to our deep dive, everyone."},
        {time: 2, text: "Today we're going to be talking all about animals."},
        {time: 4, text: "Oh, I love animals."},
        {time: 5, text: "Are we going to see some cool pictures?"},
        {time: 7, text: "Yes, we are going to see some cool pictures and learn some new words too."},
        {time: 11, text: "Awesome."},
        {time: 11, text: "I'm ready."},
        {time: 12, text: "OK, so first let's look at this owl."},
        {time: 15, text: "Oh, look at its big eyes."},
        {time: 17, text: "Yeah, owls have really big eyes."},
        {time: 19, text: "They need them to see at night."},
        {time: 21, text: "What do they need to see at night?"},
        {time: 22, text: "Is that when they hunt?"},
        {time: 22, text: "That's right."},
        {time: 23, text: "Owls sleep during the day, and they wake up at night to hunt."},
        {time: 26, text: "What do they hunt for?"},
        {time: 27, text: "They hunt for small animals like mice and voles."},
        {time: 30, text: "Those owls are so cool."},
        {time: 31, text: "So where do these owls live?"},
        {time: 33, text: "These owls live in England."},
        {time: 35, text: "England."},
        {time: 36, text: "Can you point to England on the map for me?"},
        {time: 38, text: "Sure."},
        {time: 39, text: "England is this island right here."},
        {time: 41, text: "Can you say England?"},
        {time: 42, text: "England."},
        {time: 42, text: "Great job."},
        {time: 43, text: "Yeah."},
        {time: 43, text: "OK."},
        {time: 44, text: "Now look at this funny little animal."},
        {time: 46, text: "It's pink and it has a shell."},
        {time: 49, text: "That's right."},
        {time: 50, text: "This is a pink fairy armadillo."},
        {time: 52, text: "Pink fairy armadillo."},
        {time: 54, text: "Wow, that's a big word."},
        {time: 55, text: "Can you say armadillo?"},
        {time: 56, text: "Armadillo."},
        {time: 57, text: "That's hard to say."},
        {time: 58, text: "You got it."},
        {time: 59, text: "Now, this armadillo is very, very small."},
        {time: 61, text: "It's only about as long as your hand."},
        {time: 63, text: "Wow, that's tiny."},
        {time: 64, text: "And see that shell on its back?"},
        {time: 66, text: "That shell helps protect the armadillo from danger."},
        {time: 70, text: "Oh, like a little shield."},
        {time: 71, text: "Yeah, just like a little shield."},
        {time: 72, text: "And look at those big claws."},
        {time: 74, text: "I see them."},
        {time: 75, text: "What are those for?"},
        {time: 76, text: "It uses those claws to dig tunnels in the sand."},
        {time: 78, text: "Tunnels."},
        {time: 79, text: "Why does it need tunnels?"},
        {time: 80, text: "It lives in those tunnels."},
        {time: 82, text: "That's where it sleeps and hides from predators."},
        {time: 84, text: "That's pretty smart."},
        {time: 85, text: "Yeah."},
        {time: 85, text: "So where does this pink fairy armadillo live?"},
        {time: 87, text: "This pink fairy armadillo lives in Argentina."},
        {time: 90, text: "Argentina."},
        {time: 91, text: "Can you point to that on the map, too, please?"},
        {time: 92, text: "Of course."},
        {time: 93, text: "Argentina's way down here in South America."},
        {time: 96, text: "See."},
        {time: 97, text: "Wow, that's far away."},
        {time: 98, text: "Now let's talk about colors."},
        {time: 100, text: "What color is this parrot?"},
        {time: 101, text: "Orange."},
        {time: 102, text: "Yep."},
        {time: 103, text: "Can you think of other things that are orange?"},
        {time: 105, text: "Hmm."},
        {time: 106, text: "Let me think."},
        {time: 109, text: "Pumpkins are orange."},
        {time: 110, text: "Good one."},
        {time: 111, text: "And basketballs are orange."},
        {time: 112, text: "That's right."},
        {time: 113, text: "OK, now look at this cute little baby."},
        {time: 115, text: "Oh, it's a baby monkey."},
        {time: 116, text: "Yes, it's a baby orangutan with its mommy orangutan."},
        {time: 120, text: "What's an orangutan?"},
        {time: 121, text: "An orangutan is a type of ape."},
        {time: 123, text: "They live in the rainforest and they are very good at climbing trees."},
        {time: 127, text: "Wow."},
        {time: 128, text: "Why is the baby holding onto its mommy?"},
        {time: 130, text: "Baby orangutans stay with their mommies for a long time."},
        {time: 133, text: "The mommies teach them everything they need to know about surviving in the rainforest."},
        {time: 137, text: "That's nice."},
        {time: 138, text: "They learn how to climb trees and find food."},
        {time: 140, text: "Yep."},
        {time: 141, text: "They even learn how to build nests in the trees."},
        {time: 143, text: "Then nests like birds?"},
        {time: 145, text: "Yeah, kind of like birds."},
        {time: 146, text: "They make their nests out of leaves and branches high up in the trees."},
        {time: 149, text: "Cool."},
        {time: 150, text: "So where do these orangutans live?"},
        {time: 152, text: "Orangutans live on the islands of Borneo and Sumatra."},
        {time: 156, text: "Borneo and Sumatra."},
        {time: 157, text: "I don't know where those are."},
        {time: 158, text: "Let me show you on the map."},
        {time: 159, text: "Borneo and Sumatra are these islands right here in Southeast Asia."},
        {time: 163, text: "I see."},
        {time: 164, text: "OK."},
        {time: 165, text: "Are you ready for a game?"},
        {time: 166, text: "Yes."},
        {time: 166, text: "I love games."},
        {time: 168, text: "What game are we going to play?"},
        {time: 169, text: "We are going to play a matching game."},
        {time: 171, text: "Look at this walrus that has a funny thing on its face."},
        {time: 174, text: "It's called a mustache."},
        {time: 176, text: "A mustache?"},
        {time: 177, text: "Can I try to spell that word?"},
        {time: 179, text: "MUSTACHE."},
        {time: 182, text: "Mustache."},
        {time: 183, text: "You got it."},
        {time: 184, text: "Now look at this porcupine."},
        {time: 185, text: "What are those sharp, pointy things on its back?"},
        {time: 188, text: "Those look pokey."},
        {time: 189, text: "What are they called?"},
        {time: 189, text: "Those are called quills."},
        {time: 191, text: "Quills."},
        {time: 191, text: "How do you spell that?"},
        {time: 192, text: "QUILLS."},
        {time: 194, text: "Quills."},
        {time: 195, text: "The quills help protect the porcupine from predators."},
        {time: 198, text: "So if another animal tries to attack the porcupine, it gets poked by the quills."},
        {time: 202, text: "Exactly."},
        {time: 202, text: "Now look at this penguin."},
        {time: 203, text: "What is covering its body?"},
        {time: 206, text: "Feathers."},
        {time: 206, text: "That's right."},
        {time: 207, text: "Birds have feathers."},
        {time: 208, text: "Can you spell feathers?"},
        {time: 209, text: "FEATHERS."},
        {time: 212, text: "Feathers."},
        {time: 213, text: "Great job."},
        {time: 214, text: "Now let's look at this animal."},
        {time: 215, text: "It has big horns on its head."},
        {time: 217, text: "Wow, those are big horns."},
        {time: 218, text: "What is that animal called?"},
        {time: 220, text: "That's called an ibex."},
        {time: 221, text: "Ibex."},
        {time: 222, text: "Hmm."},
        {time: 223, text: "IBEX."},
        {time: 224, text: "Exactly."},
        {time: 225, text: "And last but not least, look at this monkey."},
        {time: 227, text: "It has long, pointy teeth called tusks."},
        {time: 230, text: "Tusks."},
        {time: 231, text: "Wow."},
        {time: 231, text: "What does it use its tusks for?"},
        {time: 233, text: "Monkeys use their tusks to eat fruit and to protect themselves from danger."},
        {time: 236, text: "So tusks are like special teeth."},
        {time: 238, text: "That's right."},
        {time: 238, text: "OK, now let's learn about hyenas."},
        {time: 240, text: "Hyenas."},
        {time: 241, text: "Are those the animals that kind of look like dogs, but they're not dogs?"},
        {time: 244, text: "That's right."},
        {time: 244, text: "Hyenas are not dogs, but they're related to dogs."},
        {time: 247, text: "And they live in big families called clans."},
        {time: 249, text: "Clans."},
        {time: 250, text: "What's a clan?"},
        {time: 251, text: "A clan is a group of animals that live together and help each other."},
        {time: 254, text: "Oh, so they're like a team?"},
        {time: 256, text: "Exactly."},
        {time: 257, text: "They work together to hunt and to protect their territory."},
        {time: 259, text: "That's cool."},
        {time: 260, text: "So where do these hyenas live?"},
        {time: 263, text: "Hyenas live in many parts of Africa, including a country called Botswana."},
        {time: 266, text: "Botswana."},
        {time: 267, text: "Can you see that on the map?"},
        {time: 268, text: "Sure."},
        {time: 269, text: "Botswana is right here in southern Africa."},
        {time: 271, text: "Oh, I see it."},
        {time: 272, text: "Are there other animals that live in Botswana too?"},
        {time: 274, text: "Yes, lots of other animals live in Botswana."},
        {time: 277, text: "Like bat-eared foxes."},
        {time: 279, text: "Bat-eared foxes."},
        {time: 280, text: "What are those?"},
        {time: 281, text: "Bat-eared foxes are small foxes with really big ears."},
        {time: 284, text: "Oh, I bet they can hear really well then."},
        {time: 286, text: "And lions live in Botswana too."},
        {time: 287, text: "Wow, lions."},
        {time: 289, text: "Those are big and scary."},
        {time: 290, text: "And zebras with their black and white stripes."},
        {time: 292, text: "Zebras are cool."},
        {time: 293, text: "I like their stripes."},
        {time: 294, text: "And hippos too."},
        {time: 295, text: "Hippos."},
        {time: 295, text: "Those are the ones that love to swim, right?"},
        {time: 297, text: "That's right."},
        {time: 298, text: "Hippos spend a lot of time in the water to stay cool."},
        {time: 300, text: "That's a good idea."},
        {time: 302, text: "OK."},
        {time: 302, text: "Are you ready for another game?"},
        {time: 303, text: "Yes."},
        {time: 304, text: "What's this game about?"},
        {time: 305, text: "This game is about land animals and water animals."},
        {time: 310, text: "Can you tell me which animals live on land and which animals live in the water?"},
        {time: 314, text: "Sounds fun."},
        {time: 315, text: "I think I can do that."},
        {time: 316, text: "OK, first up, is the giant panda land or water?"},
        {time: 320, text: "Giant panda?"},
        {time: 322, text: "I think pandas live on land."},
        {time: 324, text: "You're right."},
        {time: 325, text: "Giant pandas live in the mountains of China and they eat bamboo."},
        {time: 328, text: "Cool."},
        {time: 329, text: "OK, what's next?"},
        {time: 330, text: "Next is an orca."},
        {time: 331, text: "Land or water?"},
        {time: 333, text: "Oh, that's a whale."},
        {time: 334, text: "Orcas live in the water."},
        {time: 336, text: "That's right."},
        {time: 336, text: "Orcas are sometimes called killer whales, but they are actually dolphins."},
        {time: 340, text: "Whoa, I didn't know that."},
        {time: 341, text: "How about a clownfish?"},
        {time: 342, text: "Land or water?"},
        {time: 343, text: "Clownfish."},
        {time: 345, text: "I think those live in the water too."},
        {time: 347, text: "Yep, you're on a roll."},
        {time: 348, text: "Clownfish live in coral reefs and they are very colorful."},
        {time: 352, text: "OK, my turn to ask."},
        {time: 353, text: "How about a giraffe?"},
        {time: 355, text: "Land or water?"},
        {time: 356, text: "A giraffe."},
        {time: 357, text: "Giraffes have long necks, so they can reach leaves high up in the trees."},
        {time: 360, text: "So that means they live on land."},
        {time: 362, text: "You got it."},
        {time: 363, text: "How about an emu?"},
        {time: 364, text: "Land or water?"},
        {time: 366, text: "That's a kind of bird, right?"},
        {time: 367, text: "But I don't think emus can fly."},
        {time: 369, text: "That's right."},
        {time: 369, text: "Emus can't fly."},
        {time: 370, text: "But they can run really fast."},
        {time: 371, text: "Where do they live?"},
        {time: 373, text: "They live on land."},
        {time: 375, text: "Now it's my turn again."},
        {time: 376, text: "How about a monkey?"},
        {time: 377, text: "Land or water?"},
        {time: 379, text: "Monkeys live in trees, so they live on land."},
        {time: 382, text: "Good job."},
        {time: 383, text: "You're getting so good at this."},
        {time: 384, text: "I know, it's fun."},
        {time: 385, text: "OK, how about a crayfish?"},
        {time: 387, text: "Land or water?"},
        {time: 389, text: "That sounds like a water animal to me."},
        {time: 391, text: "That's right."},
        {time: 392, text: "Crayfish live in freshwater rivers and lakes."},
        {time: 394, text: "OK, last one."},
        {time: 395, text: "Sea star."},
        {time: 396, text: "Land or water?"},
        {time: 398, text: "Sea star."},
        {time: 399, text: "Where do you think sea stars live?"},
        {time: 401, text: "In the water."},
        {time: 402, text: "You got it."},
        {time: 403, text: "Sea stars live in the ocean, and they come in lots of different colors."},
        {time: 406, text: "I love sea stars."},
        {time: 407, text: "They're so pretty."},
        {time: 408, text: "Me too."},
        {time: 409, text: "Now let's look at this deer."},
        {time: 410, text: "It has big antlers on its head."},
        {time: 412, text: "Wow, those antlers are huge."},
        {time: 413, text: "What kind of deer is that?"},
        {time: 415, text: "This is called a roe deer."},
        {time: 416, text: "A roe deer?"},
        {time: 417, text: "Can you say that again, please?"},
        {time: 418, text: "Red deer."},
        {time: 418, text: "Can you say roe deer?"},
        {time: 419, text: "Roe deer."},
        {time: 420, text: "Good job."},
        {time: 421, text: "Now, do you know why male roe deer have antlers?"},
        {time: 424, text: "Is it to protect themselves?"},
        {time: 426, text: "Yes."},
        {time: 427, text: "But they also use their antlers to fight other male roe deer."},
        {time: 430, text: "Why do they fight?"},
        {time: 431, text: "They fight to show who is stronger and to win the attention of female roe deer."},
        {time: 435, text: "So it's like a competition?"},
        {time: 437, text: "Exactly."},
        {time: 438, text: "Where do you think roe deer live?"},
        {time: 440, text: "Are they in Africa too?"},
        {time: 441, text: "Nope."},
        {time: 442, text: "Roe deer don't live in Africa."},
        {time: 443, text: "They live in Scotland, England, and Wales."},
        {time: 446, text: "Scotland, England, and Wales."},
        {time: 447, text: "Are those all in the same place?"},
        {time: 448, text: "They are."},
        {time: 448, text: "They are all countries that are part of the United Kingdom."},
        {time: 451, text: "Can you show me on the map?"},
        {time: 452, text: "Sure."},
        {time: 453, text: "Scotland, England, and Wales are all located on this island right here."},
        {time: 456, text: "Oh, wow."},
        {time: 457, text: "So the roe deer live close to the owls."},
        {time: 459, text: "That's right."},
        {time: 460, text: "OK."},
        {time: 461, text: "Are you ready to go back in time?"},
        {time: 462, text: "You mean to meet a dinosaur?"},
        {time: 463, text: "Dinosaurs."},
        {time: 464, text: "Yes."},
        {time: 464, text: "I love dinosaurs."},
        {time: 465, text: "This dinosaur is called Corythosaurus."},
        {time: 468, text: "Corythosaurus."},
        {time: 469, text: "What a funny name."},
        {time: 470, text: "Can you say that again?"},
        {time: 471, text: "Slowly, please?"},
        {time: 472, text: "Corythosaurus."},
        {time: 474, text: "Corythosaurus."},
        {time: 475, text: "Wow, that's hard to say."},
        {time: 476, text: "What did it look like?"},
        {time: 477, text: "Corythosaurus was a big plant-eating dinosaur with a long neck and a big crest on its head."},
        {time: 483, text: "A crest."},
        {time: 484, text: "What's a crest?"},
        {time: 485, text: "A crest is a bony plate that sticks up from the top of the head."},
        {time: 489, text: "Look, you can see in this picture it looks like a helmet."},
        {time: 492, text: "Scientists think Corythosaurus might have used its crest to make loud sounds."},
        {time: 496, text: "Like to talk to other Corythosaurus, maybe."},
        {time: 499, text: "Or maybe it used its crest to attract mates."},
        {time: 502, text: "That's a cool dinosaur."},
        {time: 503, text: "I want to see more dinosaurs."},
        {time: 504, text: "We'll see more dinosaurs another time."},
        {time: 505, text: "Now let's play one last game for today."},
        {time: 507, text: "OK, I'm ready to play."},
        {time: 509, text: "Look at these pictures."},
        {time: 510, text: "Can you find the pictures whose names end with the letter T?"},
        {time: 513, text: "Let me see."},
        {time: 517, text: "Hat ends with T."},
        {time: 518, text: "Yes, good job."},
        {time: 519, text: "And tent ends with T."},
        {time: 521, text: "You got it."},
        {time: 521, text: "And peanut ends with T."},
        {time: 523, text: "That's three."},
        {time: 524, text: "You found all the pictures that end with the letter T."},
        {time: 527, text: "You are a word detective."},
        {time: 528, text: "Yay."},
        {time: 529, text: "Now get ready to meet some more amazing animals."},
        {time: 532, text: "These are our wild cards."},
        {time: 533, text: "Wild cards? How does that mean?"},
        {time: 535, text: "Wild cards are animals that are extra special and have unique features and adaptations."},
        {time: 539, text: "Oh, cool. Like superpowers?"},
        {time: 541, text: "Kind of like superpowers. First up is the Arctic wolf."},
        {time: 544, text: "Arctic wolf? What's Arctic?"},
        {time: 546, text: "Arctic means very cold and icy. The Arctic wolf lives in a very cold place."},
        {time: 551, text: "So it must have a thick coat to stay warm."},
        {time: 553, text: "That's right. Arctic wolves have thick white fur that helps them blend in with the snow and stay warm in freezing temperatures."},
        {time: 559, text: "Oh, that's smart. What else do we have?"},
        {time: 561, text: "Next is the Japanese macaque."},
        {time: 563, text: "Japanese macaque? What's a macaque?"},
        {time: 565, text: "A macaque is a type of monkey that lives in Japan."},
        {time: 567, text: "What's special about this monkey?"},
        {time: 569, text: "Japanese macaques are famous for taking baths in hot springs."},
        {time: 573, text: "Baths in hot springs? That sounds relaxing."},
        {time: 575, text: "It does. And then we have a very special fish called a harlequin ghost pipefish."},
        {time: 580, text: "A harlequin ghost pipefish. Wow. That's a long name. What does it look like?"},
        {time: 585, text: "This fish is a master of camouflage. It has a long, thin body and it can change its color to match its surroundings."},
        {time: 593, text: "Wow, that's cool. So that's like a ghost in the ocean."},
        {time: 596, text: "Exactly. And we have a tiny frog called a spring peeper."},
        {time: 599, text: "A spring peeper? Why is it called that?"},
        {time: 601, text: "Because it makes a beeping sound that you can hear in the springtime."},
        {time: 604, text: "Oh, so it's a singing frog. That's cute."},
        {time: 606, text: "And then we have a bird called a red-bellied woodpecker."},
        {time: 609, text: "A woodpecker? What does it do?"},
        {time: 610, text: "Woodpeckers use their strong beaks to peck holes in trees."},
        {time: 615, text: "Why do they do that?"},
        {time: 616, text: "They peck holes in trees to find insects to eat and to make nests."},
        {time: 620, text: "Oh, that's smart. They use their beaks like tools."},
        {time: 623, text: "And last but not least, we have the pronghorn."},
        {time: 626, text: "The pronghorn? What's a pronghorn?"},
        {time: 628, text: "A pronghorn is a type of antelope that lives in North America."},
        {time: 631, text: "What's special about the pronghorn?"},
        {time: 633, text: "The pronghorn is one of the fastest land animals in the world."},
        {time: 636, text: "Wow. I bet it can run super fast."},
        {time: 639, text: "It can run up to 60 miles per hour."},
        {time: 641, text: "That's amazing. I wish I could run that fast."},
        {time: 644, text: "Me too. Well, those are all our wild card animals for today."},
        {time: 647, text: "Wow. We saw so many amazing animals today. I learned so much."},
        {time: 650, text: "Me too. It's incredible how diverse the animal kingdom is."},
        {time: 654, text: "Yeah. There are so many different animals all over the world, and each animal has its own special adaptations that help it survive in its environment."},
        {time: 660, text: "That's what makes them so cool. It's so cool how all these different animals can survive in so many different places."},
        {time: 666, text: "I know. It's amazing, right? Like, how does that tiny little pink fairy armadillo stay safe."},
        {time: 672, text: "Oh, that's a good question. Well, remember how it has that hard shell on its back?"},
        {time: 677, text: "Yeah. It's pink, right?"},
        {time: 678, text: "Yeah. Well, that pink shell actually helps it blend in with the sand in Argentina, where it lives."},
        {time: 684, text: "So it's like camouflage."},
        {time: 685, text: "Exactly. It's like hiding in plain sight. And that shell is really strong too. It protects the armadillo from predators."},
        {time: 690, text: "So it's like a little pink tank?"},
        {time: 692, text: "Uh huh. Yeah, kind of. And don't forget those big claws, they help it dig those burrows where it lives."},
        {time: 697, text: "Oh yeah, that's right. It's like its own little underground fortress."},
        {time: 700, text: "Now let's talk about those owls again. Remember we said that they hunt at night?"},
        {time: 704, text: "Yeah. They're nocturnal, right?"},
        {time: 705, text: "Yep. And they have these amazing eyes that can see really well in the dark."},
        {time: 710, text: "So they can see their prey even when it's super dark out?"},
        {time: 713, text: "Exactly. They can spot a tiny little mouse from far away even if there's barely any light."},
        {time: 718, text: "Wow, that's like a superpower."},
        {time: 720, text: "It is pretty amazing. And their feathers are special too."},
        {time: 723, text: "What's special about their feathers?"},
        {time: 725, text: "They're super quiet. When owls fly, they don't make any noise."},
        {time: 729, text: "Oh, wow. So they can sneak up on their prey without being heard?"},
        {time: 732, text: "That's right. They're like silent ninjas of the night."},
        {time: 735, text: "Okay, now let's talk about those cute baby orangutans again."},
        {time: 738, text: "Oh yeah, the ones that live in the rainforest."},
        {time: 740, text: "Yep. Remember how they learn everything from their mommies?"},
        {time: 743, text: "Yeah. It's like they go to jungle school."},
        {time: 745, text: "It is. And they stay with their moms for a long time."},
        {time: 748, text: "Why do they stay with their moms for so long?"},
        {time: 750, text: "Because they have so much to learn. Like how to climb trees, how to find food, how to build nests."},
        {time: 755, text: "Oh yeah, those nests high up in the trees. They're pretty cool."},
        {time: 759, text: "They are. And it takes a long time for the baby orangutans to learn how to do all those things."},
        {time: 764, text: "That's why they need their mommies to teach them."},
        {time: 766, text: "Exactly. You know, hyenas are a lot like that too."},
        {time: 769, text: "Hyenas? You mean the ones that live in clans?"},
        {time: 772, text: "Yep. They live in big family groups and they work together to survive."},
        {time: 776, text: "Oh yeah, that's right. It's all about teamwork with hyenas."},
        {time: 780, text: "And remember how we said that female hyenas are the leaders of their clans?"},
        {time: 785, text: "Yeah, girl power."},
        {time: 787, text: "The females are bigger and stronger than the males and they lead the hunts and protect the territory."},
        {time: 792, text: "It's kind of like those owls we talked about. They're both nighttime hunters."},
        {time: 797, text: "That's true. But owls are solitary hunters, which means they hunt alone."},
        {time: 802, text: "And hyenas are pack hunters, which means they hunt together."},
        {time: 805, text: "That's right. Different animals have different strategies for survival."},
        {time: 808, text: "It's so cool how nature works."},
        {time: 811, text: "Speaking of cool, remember that Corythosaurus dinosaur we talked about?"},
        {time: 815, text: "Yeah, the one with the big crest on its head."},
        {time: 817, text: "Yep. Do you remember what scientists think that crest was for?"},
        {time: 822, text: "I think you said it might have been for making sounds."},
        {time: 825, text: "That's right. They think Corythosaurus might have used its crest to make loud calls."},
        {time: 829, text: "Like to talk to other Corythosaurus or to attract mates."},
        {time: 833, text: "Exactly. It's like a built-in trumpet."},
        {time: 835, text: "That's so cool. I wish I had a crest on my head."},
        {time: 838, text: "Maybe not."},
        {time: 839, text: "Speaking of those wild card animals."},
        {time: 841, text: "Yeah, those were awesome."},
        {time: 843, text: "I know. Which one was your favorite?"},
        {time: 846, text: "That's a tough one. I think I liked the harlequin ghost pipefish the best."},
        {time: 850, text: "Oh yeah. The one that can change its color to match its surroundings."},
        {time: 853, text: "Yep. That was so cool. It's like it disappears right into the coral."},
        {time: 857, text: "I know. It's like magic."},
        {time: 859, text: "And I like the spring peeper frog too. The one that sounds like sleigh bells."},
        {time: 863, text: "Me too."},
        {time: 864, text: "Yeah."},
        {time: 865, text: "It's amazing how such a tiny frog can make such a loud sound."},
        {time: 868, text: "I know, right? Nature's full of surprises."},
        {time: 871, text: "It really is."},
        {time: 872, text: "It really is. It's like all the animals in the world fit together."},
        {time: 875, text: "Yeah. Like a big puzzle. And we got to learn about so many of those puzzle pieces today."},
        {time: 879, text: "I know. And I learned some new words too."},
        {time: 882, text: "Me too. It's so much fun to learn new words."},
        {time: 885, text: "Yeah. Do you remember when we matched those animals to their body parts?"},
        {time: 889, text: "Oh yeah. Like the walrus with its mustache. Can you spell mustache again?"},
        {time: 893, text: "M U S T A C H E. Mustache."},
        {time: 896, text: "And the porcupine with its quills. Q U I L L S."},
        {time: 900, text: "And the penguin with its feathers. F E A T H E R S."},
        {time: 905, text: "We saw so many cool animals. Which wild card animal did you like the best?"},
        {time: 911, text: "That's a hard one. There were so many good ones."},
        {time: 913, text: "I know, right?"},
        {time: 914, text: "Okay, okay. I think my favorite was the Arctic wolf."},
        {time: 917, text: "Oh yeah. The one that lives in the really cold place."},
        {time: 919, text: "Yep. And it has that thick white fur to stay warm."},
        {time: 922, text: "It's like a big fluffy snowball."},
        {time: 923, text: "What about you? What was your favorite?"},
        {time: 926, text: "I think I like the Japanese macaques the best."},
        {time: 929, text: "Oh yeah. The monkeys that take baths in the hot springs."},
        {time: 931, text: "Yep. It just sounds so relaxing."},
        {time: 934, text: "I know, right? I wish I could take a bath in a hot spring."},
        {time: 937, text: "Maybe someday we can."},
        {time: 938, text: "That would be awesome."},
        {time: 939, text: "Well, that's all the time we have for today. But before we go, we have a challenge for you."},
        {time: 942, text: "Ooh, a challenge. I love challenges. What is it?"},
        {time: 945, text: "Think about all the animals we talked about today. Which one was your favorite?"},
        {time: 948, text: "Yeah, which one did you like the best?"},
        {time: 951, text: "Maybe you loved learning about owls. Or maybe you thought the pink fairy armadillo was super cool."},
        {time: 957, text: "Or maybe you really like the Corythosaurus dinosaur."},
        {time: 960, text: "Whichever animal you like the most, we encourage you to go learn more about it."},
        {time: 964, text: "Yeah, you can read books about it or watch videos."},
        {time: 968, text: "You could even ask your teacher or your parents to help you learn more."},
        {time: 971, text: "There's so much to learn about animals."},
        {time: 974, text: "The world is full of amazing creatures just waiting to be discovered."},
        {time: 977, text: "So keep exploring and keep learning. And never stop being curious."},
        {time: 981, text: "Thanks for joining us on this deep dive. We'll see you next time."},
        {time: 984, text: "Bye, everyone."}        
]